version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: plexlist-backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "5000:5000"
    command: ["sh", "entrypoint.sh"]

  frontend:
    build:
      context: ./frontend
    container_name: plexlist-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent host override
    working_dir: /app
    ports:
      - "3000:5173"
    command: ["npm", "run", "dev", "--", "--host"]
